/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package en.uog.frames;

import en.uog.dao.BookingDaoImpl;
import en.uog.dao.ValidationProvider;
import en.uog.database.PersistenceManager;
import en.uog.entities.User;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.persistence.EntityManager;

/**
 *
 * @author aziz
 */
public class ConnexionFrame extends javax.swing.JFrame implements WindowListener{
    boolean validation = true;
    /** Creates new form ConnexionFrame */
    public ConnexionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        errLogin.setText("");
        errPassword.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnInscription = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfLogin = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        errPassword = new javax.swing.JLabel();
        errLogin = new javax.swing.JLabel();
        errConnexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(506, 394));
        setMinimumSize(new java.awt.Dimension(506, 394));
        setName("connexionFrame"); // NOI18N

        jDesktopPane1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cinema Booking System");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(70, 30, 380, 50);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnLogin);
        btnLogin.setBounds(220, 290, 79, 29);

        btnInscription.setBackground(new java.awt.Color(255, 255, 255));
        btnInscription.setText("Join system : Inscription");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnInscription);
        btnInscription.setBounds(160, 330, 197, 29);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(220, 200, 80, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(230, 120, 60, 20);

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("© Copyright 2017 F.TITIKPINA");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(170, 380, 190, 16);

        txfLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLoginActionPerformed(evt);
            }
        });
        jDesktopPane1.add(txfLogin);
        txfLogin.setBounds(120, 140, 280, 26);

        txfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDesktopPane1.add(txfPassword);
        txfPassword.setBounds(120, 220, 280, 26);

        errPassword.setForeground(new java.awt.Color(255, 255, 51));
        errPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errPassword.setText("err password");
        jDesktopPane1.add(errPassword);
        errPassword.setBounds(200, 250, 120, 16);

        errLogin.setForeground(new java.awt.Color(255, 255, 51));
        errLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errLogin.setText("err login");
        jDesktopPane1.add(errLogin);
        errLogin.setBounds(200, 170, 120, 16);

        errConnexion.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        errConnexion.setForeground(new java.awt.Color(255, 102, 102));
        errConnexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errConnexion.setText("Login or Password is incorrect");
        jDesktopPane1.add(errConnexion);
        errConnexion.setBounds(150, 90, 230, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        em = PersistenceManager.getEntityManager();
        validation();
        if (validation) {
            if(this.login() != null){
                this.dispose();
                WelcomeFrame wf = new WelcomeFrame();
                wf.setVisible(true);
            }else{
                
            }
            
        } else {
           
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLoginActionPerformed

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        InscriptionFrame ifr = new InscriptionFrame();
        ifr.setVisible(true);
    }//GEN-LAST:event_btnInscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnexionFrame().setVisible(true);
            }
        });
    }
    EntityManager em = PersistenceManager.getEntityManager();
    BookingDaoImpl dao = new BookingDaoImpl();
    public void validation(){
        validation = true;
        if (!ValidationProvider.minString(txfPassword.getText(), 8)) {
            validation = false;
            errPassword.setText("Minimum = 8");
        }else{
            errPassword.setText("");
        }
    }
    private User login() {
       dao = new BookingDaoImpl();
       return dao.login(txfLogin.getText(), txfPassword.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscription;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel errConnexion;
    private javax.swing.JLabel errLogin;
    private javax.swing.JLabel errPassword;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txfLogin;
    private javax.swing.JTextField txfPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

}
