/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package en.uog.frames;

import en.uog.dao.BookingDaoImpl;
import en.uog.entities.Movie;
import en.uog.tablesmodel.AddMovieModel;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author faycal
 */
public class IFAddMovie extends javax.swing.JInternalFrame {

     public static UtilDateModel model = new UtilDateModel();
     public static JDatePanelImpl datePanel = new JDatePanelImpl(model);
     public static JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);
     
     AddMovieModel movieModel = new AddMovieModel();
     List<Movie> liste;
     BookingDaoImpl dao;
     
    /**
     * Creates new form IFAddMovie
     */
    public IFAddMovie() {
        initComponents();
        model.setValue(new Date());
        panDate.add(datePicker);
        
        tableMovie.setModel(movieModel);
        dao = new BookingDaoImpl();
        liste = dao.getAllMovies();
        movieModel.LoadMovie(liste);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfTitle = new javax.swing.JTextField();
        errLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errLogin1 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        txfAbstract = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        scrListe = new javax.swing.JScrollPane();
        tableMovie = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        panDate = new javax.swing.JPanel();
        btnAddMovie = new javax.swing.JButton();

        desktop.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Apple Chancery", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add  Movie");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktop.add(jLabel1);
        jLabel1.setBounds(130, 10, 380, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Title :");
        desktop.add(jLabel2);
        jLabel2.setBounds(50, 40, 36, 16);
        desktop.add(txfTitle);
        txfTitle.setBounds(90, 40, 290, 26);

        errLogin.setForeground(new java.awt.Color(255, 255, 51));
        errLogin.setText("err login");
        desktop.add(errLogin);
        errLogin.setBounds(390, 40, 210, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Release date :");
        desktop.add(jLabel3);
        jLabel3.setBounds(50, 170, 120, 16);

        errLogin1.setForeground(new java.awt.Color(255, 255, 51));
        errLogin1.setText("err abstract");
        desktop.add(errLogin1);
        errLogin1.setBounds(390, 70, 210, 16);

        txfAbstract.setColumns(20);
        txfAbstract.setRows(5);
        scrollPane.setViewportView(txfAbstract);

        desktop.add(scrollPane);
        scrollPane.setBounds(90, 70, 290, 84);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Abstract:");
        desktop.add(jLabel4);
        jLabel4.setBounds(16, 70, 70, 16);

        tableMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMovie.setSize(new java.awt.Dimension(620, 64));
        scrListe.setViewportView(tableMovie);

        desktop.add(scrListe);
        scrListe.setBounds(10, 210, 627, 170);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        desktop.add(btnDelete);
        btnDelete.setBounds(260, 390, 97, 29);
        desktop.add(panDate);
        panDate.setBounds(180, 170, 220, 30);

        btnAddMovie.setText("Add movie");
        btnAddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMovieActionPerformed(evt);
            }
        });
        desktop.add(btnAddMovie);
        btnAddMovie.setBounds(450, 170, 110, 29);

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMovieActionPerformed
        // TODO add your handling code here:
        Movie movie = new Movie();
        movie.setTitle(txfTitle.getText());
        movie.setMovieAbstract(txfAbstract.getText());
        Date selectDate = (Date) datePicker.getModel().getValue();
        movie.setDateRelease(selectDate);
        dao.addMovie(movie);
        dao = new BookingDaoImpl();
        liste = new ArrayList<Movie>(dao.getAllMovies());
        movieModel.LoadMovie(liste);
        tableMovie.setModel(movieModel);
    }//GEN-LAST:event_btnAddMovieActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (tableMovie.getSelectedRow() != -1) {
            Movie movie = liste.get(tableMovie.getSelectedRow());
            System.out.println(movie.getId());
            dao = new BookingDaoImpl();
            dao.delMovie(movie);
            dao = new BookingDaoImpl();
            liste = new ArrayList<Movie>(dao.getAllMovies());
            movieModel.LoadMovie(liste);
            tableMovie.setModel(movieModel);
        }else{
            System.err.println("Please select movie before");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMovie;
    private javax.swing.JButton btnDelete;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel errLogin;
    private javax.swing.JLabel errLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panDate;
    private javax.swing.JScrollPane scrListe;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tableMovie;
    private javax.swing.JTextArea txfAbstract;
    private javax.swing.JTextField txfTitle;
    // End of variables declaration//GEN-END:variables
}
