/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package en.uog.frames.clients;

import en.uog.dao.BookingDaoImpl;
import en.uog.entities.BookTicket;
import en.uog.entities.OnScreen;
import en.uog.entities.User;
import en.uog.tablesmodel.ListPuschassModel;
import en.uog.tablesmodel.ListRecommandationModel;
import java.util.List;

/**
 *
 * @author aziz
 */
public class IFPurshases extends javax.swing.JInternalFrame {

    ListPuschassModel listPuschassModel = new ListPuschassModel();
     List<BookTicket> liste;
     BookingDaoImpl dao;
     
     ListRecommandationModel listRecommandationModel = new ListRecommandationModel();
     List<OnScreen> listeOnScreens;
    /**
     * Creates new form IFPurshases
     */
    public IFPurshases(User user) {
        initComponents();
        tablePurchasse.setModel(listPuschassModel);
        dao = new BookingDaoImpl();
        liste = dao.getBookTicketByUser(user);
        listPuschassModel.LoadTicket(liste);
        
        tableRecommandation.setModel(listRecommandationModel);
        dao = new BookingDaoImpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePurchasse = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRecommandation = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        jDesktopPane1.setLayout(null);

        jButton1.setText("Print ⎙");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(520, 40, 190, 180);

        tablePurchasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePurchasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePurchasseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePurchasse);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 500, 180);

        tableRecommandation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableRecommandation);

        jDesktopPane1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 260, 500, 180);

        jButton2.setText("Buy ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton2)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(520, 260, 190, 180);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePurchasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePurchasseMouseClicked
        // TODO add your handling code here:
        if (tablePurchasse.getSelectedRow()!=-1) {
            System.err.println("Selction : "+tablePurchasse.getSelectedRow());
            BookTicket bookTicket = liste.get(tablePurchasse.getSelectedRow());
            dao = new BookingDaoImpl();
            listRecommandationModel = new ListRecommandationModel();
            tableRecommandation.setModel(listRecommandationModel);
            System.err.println("Movie : "+bookTicket.getOnScreen().getMovie().getTitle());
            System.err.println("Categorie : "+bookTicket.getOnScreen().getMovie().getCategorie().getName());
            listeOnScreens = dao.findOnScreenByCategorie(bookTicket.getOnScreen().getMovie().getCategorie().getName());             
            listRecommandationModel.LoadOnScreen(listeOnScreens);
            
        }
    }//GEN-LAST:event_tablePurchasseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePurchasse;
    private javax.swing.JTable tableRecommandation;
    // End of variables declaration//GEN-END:variables
}
