/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package en.uog.frames.clients;

import en.uog.dao.BookingDaoImpl;
import en.uog.entities.BookTicket;
import en.uog.entities.OnScreen;
import en.uog.entities.User;
import en.uog.tablesmodel.ListPuschassModel;
import en.uog.tablesmodel.ListRecommandationModel;
import java.util.List;

/**
 *
 * @author aziz
 */
public class IFPurshases extends javax.swing.JInternalFrame {

    ListPuschassModel listPuschassModel = new ListPuschassModel();
     List<BookTicket> liste;
     BookingDaoImpl dao;
     
     ListRecommandationModel listRecommandationModel = new ListRecommandationModel();
     List<OnScreen> listeOnScreens;
    /**
     * Creates new form IFPurshases
     */
    public IFPurshases(User user) {
        initComponents();
        tablePurchasse.setModel(listPuschassModel);
        dao = new BookingDaoImpl();
        liste = dao.getBookTicketByUser(user);
        listPuschassModel.LoadTicket(liste);
        
        tableRecommandation.setModel(listRecommandationModel);
        dao = new BookingDaoImpl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePurchasse = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRecommandation = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jDesktopPane1.setLayout(null);

        tablePurchasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePurchasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePurchasseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePurchasse);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 700, 180);

        tableRecommandation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableRecommandation);

        jDesktopPane1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 260, 700, 180);

        jLabel1.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Our recommendations");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(280, 235, 180, 20);

        jLabel2.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Previous Purchases");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(270, 10, 180, 20);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePurchasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePurchasseMouseClicked
        // TODO add your handling code here:
        if (tablePurchasse.getSelectedRow()!=-1) {
            System.err.println("Selction : "+tablePurchasse.getSelectedRow());
            BookTicket bookTicket = liste.get(tablePurchasse.getSelectedRow());
            dao = new BookingDaoImpl();
            listRecommandationModel = new ListRecommandationModel();
            tableRecommandation.setModel(listRecommandationModel);
            System.err.println("Movie : "+bookTicket.getOnScreen().getMovie().getTitle());
            System.err.println("Categorie : "+bookTicket.getOnScreen().getMovie().getCategorie().getName());
            listeOnScreens = dao.findOnScreenByCategorie(bookTicket.getOnScreen().getMovie().getCategorie().getName());             
            listRecommandationModel.LoadOnScreen(listeOnScreens);
            
        }
    }//GEN-LAST:event_tablePurchasseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePurchasse;
    private javax.swing.JTable tableRecommandation;
    // End of variables declaration//GEN-END:variables
}
