/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package en.uog.frames.clients;

import com.google.zxing.WriterException;
import com.itextpdf.text.DocumentException;
import en.uog.dao.BookingDaoImpl;
import en.uog.dao.CreatePdf;
import en.uog.dao.SendMail;
import en.uog.entities.BookTicket;
import en.uog.entities.Categorie;
import en.uog.entities.OnScreen;
import en.uog.entities.User;
import en.uog.tablesmodel.UserModel;
import en.uog.tablesmodel.clients.ModelListProgram;
import java.awt.event.ItemEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aziz
 */
public class IFViewPrograms extends javax.swing.JInternalFrame {

    ModelListProgram programModel = new ModelListProgram();
     List<OnScreen> liste;
     BookingDaoImpl dao;
     List<Categorie> listeCategories;
    /**
     * Creates new form IFViewPrograms
     */
    User currentUser = new User();
    public IFViewPrograms(User user) {
        initComponents();
        currentUser = user;
       
        tableProgram.setModel(programModel);
        dao = new BookingDaoImpl();
        liste = dao.getAllOnScreen();
        programModel.LoadOnScreen(liste);
        
        listeCategories = dao.getAllCategorie();
        comboCategorie.removeAllItems();
        comboCategorie.addItem("All categories");
        for (Categorie categorie : listeCategories) {
            comboCategorie.addItem(categorie.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        scrilll = new javax.swing.JScrollPane();
        tableProgram = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDetails = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboCategorie = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnBuy = new javax.swing.JButton();

        jDesktopPane1.setLayout(new java.awt.BorderLayout());

        tableProgram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProgram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProgramMouseClicked(evt);
            }
        });
        scrilll.setViewportView(tableProgram);

        jDesktopPane1.add(scrilll, java.awt.BorderLayout.CENTER);

        txaDetails.setColumns(20);
        txaDetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txaDetails.setRows(5);
        jScrollPane1.setViewportView(txaDetails);

        jDesktopPane1.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Marker Felt", 0, 13)); // NOI18N
        jLabel1.setText("Categorie : ");
        jPanel1.add(jLabel1);

        comboCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCategorie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboCategorieItemStateChanged(evt);
            }
        });
        comboCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboCategorieMouseClicked(evt);
            }
        });
        jPanel1.add(comboCategorie);

        jDesktopPane1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnBuy.setFont(new java.awt.Font("Marker Felt", 0, 13)); // NOI18N
        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuy, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        String[] choices = { "1", "2", "3", "4" };
    String input = (String) JOptionPane.showInputDialog(null, "How many tichkets do you want ?",
        "Number of Tickets", JOptionPane.QUESTION_MESSAGE, null, 
        choices, // Array of choices
        choices[0]); // Initial choice
        if (input==null) {
            this.setVisible(true);
            System.err.println("nullllll");
        }else{
            this.setVisible(true);
                    for (int i = 0; i < Integer.parseInt(input); i++) {
                        	
                    if (tableProgram.getSelectedRow() != -1) {
                    OnScreen onScreen = liste.get(tableProgram.getSelectedRow());
                    dao = new BookingDaoImpl();
                    BookTicket bookTicket = new BookTicket();
                    bookTicket.setMovieName(onScreen.getMovie().getTitle());
                    bookTicket.setUser(currentUser);
                    bookTicket.setDatePurchase(new Date());
                    bookTicket.setOnScreen(dao.findOnScreenById(onScreen.getId()));
                    dao.addBookTicket(bookTicket);
                    String file = null;
                    try {
                        file = CreatePdf.createPdf(currentUser.getFirstname() + " " + currentUser.getLastName(), bookTicket.getOnScreen().getMovie().getTitle(), bookTicket.getOnScreen().getPrice());
                    } catch (DocumentException ex) {
                        Logger.getLogger(IFViewPrograms.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (URISyntaxException ex) {
                        Logger.getLogger(IFViewPrograms.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(IFViewPrograms.class.getName()).log(Level.SEVERE, null, ex);
                    }   catch (WriterException ex) {
                            Logger.getLogger(IFViewPrograms.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    SendMail.SendReceiptOfPayment(currentUser.getEmail(), file);

                }else{
                    System.err.println("Please select user before");
                }
                    this.setVisible(true);

            }
        }
        

    }//GEN-LAST:event_btnBuyActionPerformed

    private void tableProgramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProgramMouseClicked
        // TODO add your handling code here:
        OnScreen onScreen = liste.get(tableProgram.getSelectedRow());
        txaDetails.setText("Abstract : "+onScreen.getMovie().getMovieAbstract());
    }//GEN-LAST:event_tableProgramMouseClicked

    private void comboCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCategorieMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCategorieMouseClicked

    private void comboCategorieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboCategorieItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            if (comboCategorie.getSelectedIndex() == 0) {
            tableProgram.setModel(programModel);
            dao = new BookingDaoImpl();
            liste = dao.getAllOnScreen();
            programModel.LoadOnScreen(liste);
        
            listeCategories = dao.getAllCategorie();
        }else{
                try {
                    int cat = listeCategories.get(comboCategorie.getSelectedIndex()-1).getId();
                    System.err.println(cat);
                    tableProgram.setModel(programModel);
                    dao = new BookingDaoImpl();
                    liste = dao.getAllOnScreenByCategorie(cat);
                    programModel.LoadOnScreen(liste);
                } catch (Exception e) {
                }
            
        }
        }
    }//GEN-LAST:event_comboCategorieItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JComboBox<String> comboCategorie;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrilll;
    private javax.swing.JTable tableProgram;
    private javax.swing.JTextArea txaDetails;
    // End of variables declaration//GEN-END:variables
}
